// The ranked-mod whitelist (docs/CONSTRAINTS.md item 17): whether loading a mod keeps the server
// ranked, for an installed mod (Mods) and for one not installed yet
// (Workshop).
//
// The list is the "Required items" of a Workshop item the engine reads at
// boot, and Lua cannot see the engine's copy. The mod's `getwhitelist` reads
// the item's page from Steam instead, at most once an hour. Without the mod,
// or until the server has a list, the panel uses the copy it ships
// (whitelist.json, regenerated by tools/make-whitelist.py), and says how old
// it is: a mod whitelisted after that date shows as not whitelisted.
//
// The engine never checks its hotfix mods (NSL Badges, UWE Hotfix 344), so
// they count as whitelisted. It does check a mod's own required items, which
// this cannot see.

import { ShieldCheck, ShieldQuestionMark, ShieldX } from "lucide-preact";
import { useEffect, useState } from "preact/hooks";
import shipped from "../whitelist.json";
import { whitelist as whitelistResource } from "../store/resources";
import { dateTime } from "./format";
import { StatusIcon } from "./Icon";

export interface Whitelist {
  /** "server": the mod read it from Steam; "shipped": the panel's own copy. */
  source: "server" | "shipped";
  /** Unix seconds. */
  readAt: number;
  ids: Set<string>;
  hotfix: Set<string>;
  /** The server is reading Steam now. */
  fetching: boolean;
  /** Why the server has no fresh list, when it said. */
  error: string | null;
}

export type WhitelistVerdict = "whitelisted" | "hotfix" | "not" | "unknown";

const shippedList: Whitelist = {
  source: "shipped",
  readAt: Date.parse(shipped.read_at) / 1000,
  ids: new Set(shipped.whitelist.map((m) => m.id)),
  hotfix: new Set(shipped.hotfix.map((m) => m.id)),
  fetching: false,
  error: null,
};

/** While the server reads Steam, ask again this soon. */
const kFetchingPollMs = 2000;

/**
 * The best list there is: the server's, else the shipped one. Asks the server
 * only when it runs the mod; a stock server would answer the state blob.
 */
export function useWhitelist(hasMod: boolean): Whitelist {
  const [, force] = useState(0);
  useEffect(() => {
    if (!hasMod) return;
    return whitelistResource.subscribe(() => force((n) => n + 1));
  }, [hasMod]);
  const res = whitelistResource.get();
  const data = hasMod ? res.data : null;

  useEffect(() => {
    if (!data?.fetching) return;
    const t = setTimeout(() => void whitelistResource.refresh(), kFetchingPollMs);
    return () => clearTimeout(t);
  }, [data]);

  if (!hasMod) return shippedList;
  if (data && data.readAt !== null) {
    return {
      source: "server", readAt: data.readAt,
      ids: new Set(data.whitelist), hotfix: new Set(data.hotfix),
      fetching: data.fetching, error: data.error,
    };
  }
  return {
    ...shippedList,
    fetching: data?.fetching ?? res.loading,
    error: data?.error ?? res.error?.message ?? null,
  };
}

/** Whitelisted or not, by the hex id the rest of the API uses. */
export function whitelistVerdict(list: Whitelist, hexId: string): WhitelistVerdict {
  if (!/^[0-9a-f]{1,16}$/i.test(hexId)) return "unknown";
  const id = BigInt(`0x${hexId}`).toString();
  if (list.hotfix.has(id)) return "hotfix";
  return list.ids.has(id) ? "whitelisted" : "not";
}

/** Where the list came from, for a tooltip. */
function sourceText(list: Whitelist): string {
  return list.source === "server"
    ? `Steam's whitelist, read by the server ${dateTime(list.readAt)}`
    : `the whitelist shipped with the panel, read ${dateTime(list.readAt)}`;
}

export function WhitelistIcon({ list, hexId }: { list: Whitelist; hexId: string }) {
  switch (whitelistVerdict(list, hexId)) {
    case "whitelisted":
      return <StatusIcon icon={ShieldCheck} label="whitelisted" tone="ok"
                         title={`ranked servers can load it (${sourceText(list)})`} />;
    case "hotfix":
      return <StatusIcon icon={ShieldCheck} label="whitelisted" tone="ok"
                         title="one of the server's hotfix mods, which ranking never checks" />;
    case "not":
      return <StatusIcon icon={ShieldX} label="not whitelisted" tone="warn"
                         title={list.source === "server"
                           ? `loading it turns ranking off (${sourceText(list)})`
                           : `not on ${sourceText(list)}: loading it turns ranking off, `
                             + "unless it was whitelisted since"} />;
    case "unknown":
      return <StatusIcon icon={ShieldQuestionMark} label="whitelist unknown" tone="dim"
                         title="not a workshop id" />;
  }
}

/** The server's reason as a sentence: its texts do not all end in a stop. */
const sentence = (text: string) => (/[.!?]$/.test(text) ? text : `${text}.`);

/** One line on where the whitelist came from and how old it is. */
export function WhitelistSource({ list, hasMod }: { list: Whitelist; hasMod: boolean }) {
  const count = `${list.ids.size} mods`;
  if (list.source === "server") {
    return (
      <p class="muted form-hint whitelist-source" data-source="server">
        Whitelist: Steam's, read by the server {dateTime(list.readAt)} ({count}).
        {list.fetching && " Reading it again now."}
        {list.error && <span class="tone-warn"> The last read failed: {sentence(list.error)}</span>}
      </p>
    );
  }
  let why;
  if (!hasMod) why = "a stock server cannot read Steam's.";
  else if (list.error) why = <span class="tone-warn">the server could not read Steam's: {sentence(list.error)}</span>;
  else if (list.fetching) why = "the server is reading Steam's now.";
  else why = "the server has not read Steam's yet.";
  return (
    <p class="muted form-hint whitelist-source" data-source="shipped">
      Whitelist: the copy shipped with the panel, read {dateTime(list.readAt)} ({count}),
      because {why} A mod whitelisted since then shows as not whitelisted.
    </p>
  );
}
